plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'coach-sun-training'

include 'java-foundations'
include 'robot-math'

project(':java-foundations').projectDir = file('example_code/java-foundations')
project(':robot-math').projectDir       = file('example_code/robot-math')
